FROM ubuntu:noble
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iptables iproute2 iputils-ping iperf3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
