FROM mirror.gcr.io/library/ubuntu:noble
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iperf3 iproute2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
