apiVersion: v1
kind: Service
metadata:
  name: oai-gnb
  labels:
    app: oai-gnb
spec:
  selector:
    app: oai-gnb
  ports:
    - name: rfsim
      port: 4043
      targetPort: 4043
    - name: ul-control
      port: 8000
      targetPort: 8000
    - name: gtp-u
      port: 2152
      protocol: UDP
      targetPort: 2152
    - name: ngap
      port: 38412
      protocol: SCTP
      targetPort: 38412
