apiVersion: v1
kind: Service
metadata:
  name: oai-amf
  labels:
    app: oai-amf
spec:
  selector:
    app: oai-amf
  ports:
    - name: ngap
      port: 38412
      targetPort: 38412
      protocol: SCTP
    - name: sbi
      port: 80
      targetPort: 80
