apiVersion: v1
kind: Service
metadata:
  name: oai-smf
  labels:
    app: oai-smf
spec:
  selector:
    app: oai-smf
  ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
    - name: sbi
      port: 80
      targetPort: 80
