apiVersion: v1
kind: Service
metadata:
  name: oai-upf
  labels:
    app: oai-upf
spec:
  selector:
    app: oai-upf
  ports:
    - name: gtp-u
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
